### ISSUE TITLE
12/5 issues

### ISSUE THREAD

**Issue by menuin** [Hanyang-UDONG/UDONG-museum#14]
- [x] delete photo, delete exhibition  : get -> post로 변경

https://github.com/Hanyang-UDONG/UDONG-museum/blob/49a145c4d5fdb426abd2af4997980f5d553b1fcf/server/routes/photos.js#L62-L71

- [x] get user's exhibitions api 추가 : GET_USER_EXHIBITIONS(uid) 내 전시회 가져오기
- [x] create exhibition : 전시회에 사용된 사진의 used(false -> true), exhibition 필드 수정

https://github.com/Hanyang-UDONG/UDONG-museum/blob/49a145c4d5fdb426abd2af4997980f5d553b1fcf/server/routes/exhibitions.js#L9-L22

- [x]  exhibition photo listup

**Comment by parkjineon** [comment]
//전시회에 등록된 사진 
```
router.get('/:exhibitionId/photos',(req,res)=>{
    Photo.find({exhibition: req.params.exhibitionId},(err, photos)=>{
        if(err){
            return res.status(400).send(err);
        }
        return res.status(200).json({
            getExhibitionPhotosSuccess: true, 
            photos: photos
        })
    })
})
```
