### ISSUE TITLE
issue test

### ISSUE THREAD

**Issue by menuin** [Hanyang-UDONG/UDONG-museum#3]
https://github.com/Hanyang-UDONG/UDONG-museum/blob/55c6397853f3d8bde48eb666780914d9b043ef92/server/routes/users.js#L12-L14

**Comment by menuin** [comment]
비밀번호 길이 검사가 5자리 이하로 되어 있어요

**Comment by menuin** [comment]
비밀번호 길이 검사가 5자리 이하로 되어 있어요

**Comment by parkjineon** [comment]
수정 완료
